### ISSUE TITLE
Add privileged get balance call.

### ISSUE THREAD

**Issue by marcopeereboom** [decred/dcrtime#29]
We need to be able to obtain the wallet balance through dcrtime. This provides 2 important features.
a) We know if the wallet is up and responding
b) We can monitor the balance a little bit easier

**Comment by sefbkn** [comment]
I'll pick this one up.

**Comment by Tsunekazu** [comment]
> I'll pick this one up.

Any progress?

**Comment by sefbkn** [comment]
@Tsunekazu There is a pull request linked to this issue.

**Comment by amassarwi** [comment]
Added in #52 & can be closed
