### ISSUE TITLE
Add abilty to submit hash directly

### ISSUE THREAD

**Issue by jzbz** [decred/dcrtime#43]
Add a way to pass `dcrtime` a SHA256 hash directly to be anchored as opposed to providing it with a file that it hashes and anchors.
So instead of doing `dcrtime -v -file <filename>` something like `dcrtime -v -hash <hash>`.

**Comment by marcopeereboom** [comment]
I thought we had that magic but it turns out it was to treat a filename as a hash. So this is going to have to be slightly magical in order to keep that interface in tact. That said I agree we need this functionality.
