### ISSUE TITLE
Allow querying for latest anchor (time)

### ISSUE THREAD

**Issue by matheusd** [decred/dcrtime#66]
This would be helpful in determining if the anchoring process is working. I'm doing some testnet tests and I'm unsure whether the anchoring process is working as intended or not. 

Also, ideally in testnet we could anchor more frequently than in hourly increments.

I'm thinking of a new endpoint and client command that returns: latest anchor tx, time and merkle root.

**Comment by marcopeereboom** [comment]
What are you suggesting here? What information do you exactly want to see?

**Comment by matheusd** [comment]
To expand a bit, the point of this would be to run something such as `dcrtime --lastanchortime` and get back the block height, tx id and timestamp of the last time dcrtime successfully anchored something so that I could immediately figure out something like "dcrtime has last dropped anchor 24h hours ago, something is off and we need to get support on it"

**Comment by amassarwi** [comment]
Sure thing, will do
