### ISSUE TITLE
Unachored digest bug on restart

### ISSUE THREAD

**Issue by lukebp** [decred/dcrtime#73]
Reproduce instructions:
1. Submit a digest
2. Restart dcrtimed before the digest has been anchored
3. Wait until the next anchor cycle.  You'll notice the submitted digest does not get included in it.
3. Try to resubmit the digest and you get the already exists error.  Try to verify the digest and you get the not anchored error.  The digest is now stuck in a state of already existing but never being anchored.

**Comment by amassarwi** [comment]
Looking

**Comment by lukebp** [comment]
This was a user error on my part.  You can't change the `flushSchedule` without also changing the `duration` variable to match it.
